# API KEY config
DEEPL_API_KEY = 'YOUR API KEY'
BG_COLOR = "#E0E5EC"
FG_COLOR = "#000000"
ACCENT_COLOR = "#007ACC"
BUTTON_BG_COLOR = "#C9D1D9"
BUTTON_FG_COLOR = "#000000"
BUTTON_ACTIVE_BG_COLOR = "#A7B0B8"
ENTRY_BG_COLOR = "#FFFFFF"
TEXT_BG_COLOR = "#FFFFFF"
TEXT_FG_COLOR = "#000000"
SHADOW_COLOR = "#D1D9E6"

